---
- hosts: "{{swarm_install| default('None')}}"
  become: yes
  tasks: 
   - name: Debug
     debug: 
      var: master

   - name: Install swarm 
     include_role: 
      name: "swarm-cluster"
     vars: 
      swarm_manager: "{{swarm_install}}"
- hosts: "{{swarm_service| default('None')}}"
  become: yes
  tasks: 
   - name: Deploy Service
     include_role: 
      name: "swarm-cluster"
      tasks_from: "deploy_service.yaml"
     vars: 
      swarm_manager: "{{swarm_service}}"
