- name: Set proxy
  set_fact: 
   pip_extra_args: "--proxy {{proxy_addr}}"
  when: proxy_addr is defined

- name: Config proxy
  lineinfile: 
   path: "/etc/yum.conf"
   regexp: "^proxy=.+$"
   line: "proxy=http://{{proxy_addr}}"
  when: proxy_addr is defined

- include_tasks: 0_pre_fly_centos.yaml

- name: Install docker
  yum: 
   name: docker
   state: installed
  register: docker_install

- name: Docker config
  template: 
   src: docker
   dest: /etc/sysconfig/docker
  notify: Restart Docker

- name: Init docker service
  service: 
   name: "docker"
   state: started
  register: docker_service

- name: Set proxy
  set_fact: 
   pip_extra_args: "--proxy {{proxy_addr}}"
  when: proxy_addr is defined

- name: pip install 
  pip: 
   name: "{{item}}"
   extra_args: "{{pip_extra_args| default('')}}"
  with_items: 
   - docker
